drm: samsung: fix drm_print.h header include
Upstream reworked the drm headers in [1], as a result we need to include
the drm_print.h header explicitly here. This patch fixes the following
build issues:

samsung/cal_common/dsim_cal.h:244:25: \
  error: declaration of 'struct drm_printer' will not be visible outside of this function [-Werror,-Wvisibility]
  void __dsim_dump(struct drm_printer *p, u32 id, struct dsim_regs *regs);
                          ^
samsung/cal_9845/dsim_reg.c:2494:6: error: conflicting types for '__dsim_dump'
  void __dsim_dump(struct drm_printer *p, u32 id, struct dsim_regs *regs)
       ^
display/samsung/cal_common/dsim_cal.h:244:6: note: previous declaration is here
  void __dsim_dump(struct drm_printer *p, u32 id, struct dsim_regs *regs);
       ^

 [1] https://lore.kernel.org/all/20220421073108.19226-1-tzimmermann@suse.de/

Bug: 236216026
Signed-off-by: Carlos Llamas <cmllamas@google.com>
Change-Id: I6bbeb5c1926bd40ba7404dc664a85ef83d9ea5fb