drm: samsung: updates to drm_writeback_connector_init()
Upstream commit 57b8280a0a41 ("drm: allow passing possible_crtcs to
drm_writeback_connector_init()") refactor the API to pass possible crtcs
as a parameter. However, since we are not setting this option here let's
just pass 0 as other drivers do in such commit. This fixes the following
build issue:

samsung/exynos_drm_writeback.c:473:44: error: too few arguments to function call, expected 7, have 6
                        wb->pixel_formats, wb->num_pixel_formats);
                                                                ^

Bug: 236216026
Signed-off-by: Carlos Llamas <cmllamas@google.com>
Change-Id: I9a4ad2d6c42389bfe97e96e1f7d672dd1be3be9f