drm: samsung: fix -Wdeprecated-non-prototype
Fixes the warnings observed when upgrading the toolchain:

samsung/exynos_drm_decon.c:323:34: error: a function declaration without
a prototype is deprecated in all versions of C
[-Werror,-Wstrict-prototypes]
static int decon_get_main_dsim_id()
                                 ^
                                  void

Bug: 236798112
Test: build_slider.sh
Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>
Change-Id: I69b080b699675fe2d2368378a6b89ed5914c616d